import type { Metadata } from "next";
import { Bruno_Ace_SC, Geist, Geist_Mono, Montserrat, Press_Start_2P } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
})

const pressStart = Press_Start_2P({
  weight: "400",
  variable: "--font-press-start",
  subsets: ["latin"]
})

const brunoAce = Bruno_Ace_SC({
  weight: "400",
  variable: "--font-bruno-ace",
  subsets: ["latin"]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} ${montserrat.variable} ${pressStart.variable} ${brunoAce.variable} antialiased flex`}>
        <main className="w-full">
          <div className="relative">
            <div className="sticky top-0 z-1">
              <NavBar />
            </div>
            <div className="relative z-0">
              {children}
            </div>
            <div>
              <Footer/>
            </div>
            
          </div>
        </main>
      </body>
    </html>
  );
}
